name: Deploy Vite site to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # Optional but recommended for React Router on GitHub Pages (refresh-safe)
      - name: Add 404 fallback
        run: cp dist/index.html dist/404.html

      # Optional: ensure GitHub Pages doesn't run Jekyll
      - name: Disable Jekyll
        run: touch dist/.nojekyll

      # If you’re using a custom domain, put a CNAME file in /public and Vite copies it.
      # Otherwise, you could create it here:
      # - name: Add CNAME
      #   run: echo "app.example.com" > dist/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
